//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyMVC.Entities
{
    using CompanyMVC.Models;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class employee_vacation
    {
        public int id { get; set; }
        public int employee_id { get; set; }

        
        public int vacation_id { get; set; }

        [Display(Name = "Vacation Days")]
        [VacationDays(ErrorMessage ="Days should be in positive numbers")]
        public string vac_days { get; set; }

        [Display(Name = "Start Date")]
        [StartDate]
        public Nullable<System.DateTime> start_date { get; set; }

        [Display(Name = "End Date")]
        public Nullable<System.DateTime> end_date {
            get;
            //{
            //DateTime endDate = Convert.ToDateTime(start_date);
            //int vacDays = Convert.ToInt32(vac_days);
            //while(vacDays > 0){

            //    if (endDate.DayOfWeek != DayOfWeek.Saturday && endDate.DayOfWeek != DayOfWeek.Sunday)
            //    {

            //        endDate = endDate.AddDays(1);
            //        vacDays -= 1;

            //    }

            //}


            //return endDate;

            //}

            set;
            //{
            //}
        }
    
        public virtual employee employee { get; set; }
        public virtual vacation vacation { get; set; }
    }
}
