//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyMVC.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employee()
        {
            this.employee_vacation = new HashSet<employee_vacation>();
        }
    
        public int id { get; set; }

        [Display(Name ="Name")]
        public string name { get; set; }

        [Display(Name = "Surname")]
        public string surname { get; set; }
        public Nullable<int> personal_nr { get; set; }
        public Nullable<int> identity_card_nr { get; set; }
        public int position_id { get; set; }
        public int department_id { get; set; }
        public int work_type_id { get; set; }
        public int schedule_id { get; set; }
        public string salary { get; set; }

        [Display(Name = "Email")]
        public string email { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }

        [Display(Name = "Department")]
        public virtual department department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee_vacation> employee_vacation { get; set; }

        [Display(Name = "Position")]
        public virtual position position { get; set; }

        [Display(Name = "Schedule")]
        public virtual schedule schedule { get; set; }

        [Display(Name = "Work Type")]
        public virtual work_type work_type { get; set; }


        public string FullName
        {
            get
            {
                return name + " " + surname;
            }
        }

        public string EndDate
        {
            get
            {
                if (end_date == null)
                {
                    return "Present";
                }
                return end_date.ToString();
            }
        }

        public string WorkType
        {
            get
            {
                if (end_date != null)
                {
                    return "Left the Job";
                }
                return work_type.name.ToString();
            }
        }
    }
}
